pull_requests:
  do_not_increment_build_number: false
image: Visual Studio 2019
configuration:
  - Release RedM
  - Release FiveM
before_build:
  - nuget restore
build:
  parallel: true
  project: MenuAPI.sln
  include_nuget_references: true
  verbosity: minimal
after_build:
  - cmd: if %APPVEYOR_REPO_TAG%==true (appveyor SetVariable -Name VERSION_NAME -Value %APPVEYOR_REPO_TAG_NAME%) else (appveyor SetVariable -Name VERSION_NAME -Value dev)
  - cmd: if "%CONFIGURATION%"=="Release FiveM" (appveyor SetVariable -Name GAME -Value "FiveM") else if "%CONFIGURATION%"=="Release RedM" (appveyor SetVariable -Name GAME -Value "RedM")
  - cmd: copy "README.md" ".\MenuAPI\bin\README.md"
  - cmd: 7z a MenuAPI-%VERSION_NAME%-%GAME%.zip -r ".\MenuAPI\bin\*"
  - cmd: appveyor PushArtifact MenuAPI-%VERSION_NAME%-%GAME%.zip
deploy:
  - provider: GitHub
    release: "[Release] MenuAPI $(VERSION_NAME)"
    tag: $(VERSION_NAME)
    artifact: MenuAPI-$(VERSION_NAME)-$(GAME).zip
    draft: true
    prerelease: false
    auth_token: $(github_auth)
    on:
      APPVEYOR_REPO_TAG: true
    description: "MenuAPI release, version $(VERSION_NAME). For info check the [docs](https://docs.vespura.com/mapi) or checkout the recent commits on GitHub (the latter is your best bet if you want updated info about this version)."
after_deploy:
  - cmd: curl -H "Content-Type:application/json" -X POST -d "{\"content\":\"^<^@^&540562517806809109^>\",\"embeds\":[{\"attachments\":[{\"color\":\"#2b8ff4\",\"text\":\"A new version of %APPVEYOR_PROJECT_NAME% (**%VERSION_NAME%** for _%GAME%_) is available!\",\"title\":\"%APPVEYOR_PROJECT_NAME% (%VERSION_NAME%-%GAME%)\",\"title_link\":\"%APPVEYOR_URL%/project/%APPVEYOR_ACCOUNT_NAME%/%APPVEYOR_PROJECT_SLUG%/builds/%APPVEYOR_BUILD_ID%\",\"author_name\":\"%APPVEYOR_ACCOUNT_NAME%\",\"author_link\":\"https://github.com/%APPVEYOR_ACCOUNT_NAME%/%APPVEYOR_PROJECT_NAME%/releases/\"}]}]}" %WEBHOOK_URL_TMP%
  - cmd: curl -F "file=@MenuAPI-%VERSION_NAME%-%GAME%.zip" %WEBHOOK_URL_TMP%
on_success:
  - cmd: curl -H "Content-Type:application/json" -X POST -d "{\"embeds\":[{\"attachments\":[{\"color\":\"#45b403\",\"text\":\"Build passed!\",\"title\":\"%APPVEYOR_PROJECT_NAME% (%VERSION_NAME%-%GAME%)\",\"title_link\":\"%APPVEYOR_URL%/project/%APPVEYOR_ACCOUNT_NAME%/%APPVEYOR_PROJECT_SLUG%/builds/%APPVEYOR_BUILD_ID%\",\"author_name\":\"%APPVEYOR_ACCOUNT_NAME%\",\"author_link\":\"https://github.com/%APPVEYOR_ACCOUNT_NAME%/%APPVEYOR_PROJECT_NAME%/\"}]}]" %WEBHOOK_URL_TMP%
on_failure:
  - cmd: curl -H "Content-Type:application/json" -X POST -d "{\"embeds\":[{\"attachments\":[{\"color\":\"#f02f2f\",\"text\":\"Build failed!\",\"title\":\"%APPVEYOR_PROJECT_NAME% (%VERSION_NAME%-%GAME%)\",\"title_link\":\"%APPVEYOR_URL%/project/%APPVEYOR_ACCOUNT_NAME%/%APPVEYOR_PROJECT_SLUG%/builds/%APPVEYOR_BUILD_ID%\",\"author_name\":\"%APPVEYOR_ACCOUNT_NAME%\",\"author_link\":\"https://github.com/%APPVEYOR_ACCOUNT_NAME%/%APPVEYOR_PROJECT_NAME%/\"}]}]" %WEBHOOK_URL_TMP%